/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const storeProducts = [
  {
    id: 1,
    title: "Solang Valley",
    img: "img/solang.jpg",
    price: 6250,
    company: "Manali, Himachal Pradesh",
    days: 5,
    info: "A favorite for adventure enthusiasts, parachuting to paragliding, horse riding to driving mini-open jeeps specially available for tourists of all age groups, Solang Valley has it all. During winters, Solang valley is covered with snowmaking skiing is a popular sport here, with training institutes and trainers located in the valley to supervise skiers and train beginners. As the snow melts, skiing is taken over by zorbing.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Tosh Valley",
    img: "img/tosh.jpg",
    price: 8200,
    company: "Kasol, Himachal Pradesh",
    days: 5,
    info: "Popular for its cannabis plantations, the tranquil village of Tosh is just another example of the unparalleled natural beauty that Himachal Pradesh holds within its bounds. Located at the far end of Parvati Valley, Tosh is untouched by modernisation and fast-paced life. With its gradual terrain and the waters of river Parvati flowing through its bosom, the Tosh Kasol trek is the go-to expedition for all adrenaline junkies. The hippie culture and otherworldly vibe of this village will surely transport you to another world.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Triund",
    img: "img/triund.jpg",
    price: 10000,
    company: "Mcleodganj, Himachal Pradesh",
    days: 5,
    info: "Triund is an easy trek in Himachal Pradesh that offers you an escape into the majestic Himalayas. Situated a few kilometres from Dharamshala at an altitude of 2828 m, it is a place perfect for trekking with amazing trails offering scenic views of the entire Kangra Valley. A trek to Triund is short and simple. It can be done from either McLeodganj or Dharamkot, which is 2 km ahead of McLeodganj. The first half of the trek is a gradually inclined walk with the last 2 km from Snowline Cafe which involves a vertical climb all the way till Triund. The evening sky from Triund is a sight in itself and is a good excuse for camping here at night.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Rohtang Pass",
    img: "img/rotang.jpg",
    price: 7800,
    company: "Manali, Himachal pradesh",
    days: 5,
    info: " Located at a distance of just 51 kilometres from the main town, Rohtang Pass can be reached only by road. The pass is located at a massive height of 3978 metres, the way up the hills is a treat to the eyes. As the vehicle climbs higher on the Manali- Keylong road, the beauty of the landscape around will leave you awestruck.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Chamba",
    img: "img/chamba.jpg",
    price: 15000,
    company: "The land of Hill Kingdoms, Temples and Monasteries",
    days: 5,
    info: "Chamba is popular for its traditional handicrafts and art along with the miniature Pahari paintings - a form of Indian painting that originated from the Himalayan hill kingdoms of North India during the 17th to 19th centuries. It is also the base camp for several treks in the great Himalayan ranges. This, along with the stunning beauty and tranquil environs beckons travellers looking for an offbeat location among the much-popular Himachali towns.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Kufri",
    img: "img/kufri.jpg",
    price: 7500,
    company: "Shimla, Himachal Pradesh",
    days: 5,
    info: "Kufri is just about 10 km from Shimla and is quite a retreat if you're in Shimla and snow is something which excites you. While there's not much to see in Kufri as such, but the panoramic views and temples after a bit of trekking are worth the time. Kufri itself is mostly treated as a spot for the tourists visiting Shimla and it is advisable to club sightseeing in Shimla or nearby areas like Chail, Mashobra, Naldehra or Narkanda as well if you intend to visit Kufri. Also, Kufri is a relatively crowded and popular attraction as almost everyone visiting Shimla comes here.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Kinnaur",
    img: "img/kinnaur.jpg",
    price: 7900,
    company: "Land of God",
    days: 5,
    info: "Kinnaur, also known as Land of God is about 235 Km from Shimla and is known for its serenity and beauty of the lush green and rocky mountainscape having Satluj, Baspa and Spiti river meandering through it. A brotherly fusion of Hinduism and Buddhism at one place reflects the existence of a culture of a different sort which is well preserved by its people in this era of modernization. Hindus visit Kinnaur to see the famous Kinner Kailash, believed to be the home of Lord Shiva and the Shivaling rocks, the stories of Pandavas and their link with Kinnaur is a great attraction.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Dalhousie",
    img: "img/dalhousie.jpg",
    price: 5500,
    company: "Little Switzerland of India",
    days: 5,
    info: "Dalhousie, one of the favourite among most tourists travelling to Himanchal Pradesh is famously known for its mesmerizing natural beauty and its old world charm. This hill station was one of the most favourite summer destinations of the ruling Britishers and this is truly reflected in the majestic Victorian style mansions in this region. Situated far from the buzzing cities in the country, this quaint town transports you to a pollution-free environment in the lap of nature. Dalhousie is known for its scenic beauty has a number mountains and river streams that tourists must visit. Among them the most famous are Panch Pulla, Satdhara Falls and the Daikund peak.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Tosh",
  img: "img/tosh.jpg",
  price: 6500,
  company: "Himachal Pradesh",
  days: 5,
  info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
